# Site settings
title: Brian McGuckin
email: bmcguckin87@gmail.com
description: Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bmcguckin.com" # the base hostname & protocol for your site
paginate: 5
theme-dark: false #Set to true to change to dark website theme
future: true

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
